version: "3"

services:
  db:
    image: postgres:12.6-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./db-backup:/db-backup
    environment:
      - POSTGRES_DB=room-map
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  server:
    build: ./server
    restart: always
    environment:
      - DB_HOST=db
      - DB_DATABASE=room-map
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    ports:
      - "9101:3000"
    volumes:
      - ./wait-for-pg.sh:/wait-for-pg.sh
    command: ["/wait-for-pg.sh", "db", "node", "dist/main.js"]
  web:
    build: ./web
    restart: always
    depends_on:
      - server
    ports:
      - "9100:80"
