version: "3"

services:
  db:
    image: postgres:12.6-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./db-backup:/db-backup
    environment:
      - POSTGRES_DB=room-map
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
