AllCops:
  Exclude:
    - "Gemfile"
    - "Gemfile.lock"

Style/Documentation:
  Enabled: false
Style/FloatDivision:
  Enabled: false
Style/EndOfLine:
  EnforcedStyle: lf

Metrics/AbcSize:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/MethodLength:
  Max: 180
Metrics/BlockLength:
  Max: 180

Layout/LineLength:
  Max: 180
