name: build packages

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
      - name: Build and push Server
        uses: docker/build-push-action@v2
        with:
          context: room-map-server
          platforms: linux/amd64,linux/arm64
          push: true
          registry: ghcr.io
          repository: liubaicai/room-map-server
          tags: ghcr.io/liubaicai/room-map-server:latest